### ISSUE TITLE
Raster tiles don't load in iD

### ISSUE THREAD

**Issue by olafveerman** [orma/openroads-vn-analytics#161]
400 bad request

```
Error: Server returned HTTP 400
    at Request.<anonymous> (/opt/app/node_modules/tilejson/lib/tilejson.js:223:19)
    at Request.f (/opt/app/node_modules/tilejson/node_modules/requestretry/node_modules/fg-lodash/node_modules/lodash/dist/lodash.js:5605:23)
    at Request.<anonymous> (/opt/app/node_modules/tilejson/node_modules/requestretry/index.js:52:17)
    at Request.self.callback (/opt/app/node_modules/tilejson/node_modules/requestretry/node_modules/request/request.js:197:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/opt/app/node_modules/tilejson/node_modules/requestretry/node_modules/request/request.js:1050:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/opt/app/node_modules/tilejson/node_modules/requestretry/node_modules/request/request.js:996:12)
```

**Comment by kamicut** [comment]
I initially investigated the openroads-tilemap because the server was returning 400 errors. This stemmed from a configuration error that @matthewhanson fixed. However, right now the raster tile server is returning blank tiles. I downloaded a sample tile (for example `openroads-vn-tiles-prod/tiles/16/51664/28541.vector.pbf`) and used the following code to parse it:
```
var vtpbf = require('vt-pbf')
var VectorTile = require('vector-tile').VectorTile
var fs = require('fs');
var Pbf = require('pbf');

var data = fs.readFileSync(__dirname + '/file.pbf')
var tile = new VectorTile(new Pbf(data))
console.log(tile);
var orig = tile.layers['network'].feature(0).toGeoJSON(0, 0, 1)
console.log(JSON.stringify(orig));
```

This outputs the following geojson:
https://gist.github.com/anonymous/6ba9063d118eec1001ce573df0a9fde0

I think the coordinates must be flipped somehow when encoding the pbf @mileswwatkins. Where do you think this could be happening?

**Comment by olafveerman** [comment]
Browsing around, I have gotten tiles to show up: http://ec2-52-55-132-50.compute-1.amazonaws.com/#/en/editor/map=13.00/105.5950/20.0054&overlays=ornetwork

With satellite basemap disabled:

![image](https://user-images.githubusercontent.com/751330/31419043-87bfba5a-ae07-11e7-9cf5-76de6ae1321a.png)

But it only shows on this zoom level!

cc @kamicut @mileswwatkins

**Comment by mileswwatkins** [comment]
Huh, at first I thought that this was because of diverging branches between `openroads-tiler` and `openroads-vn-tiler`, but apparently not:

- https://github.com/orma/openroads-tiler/commits/develop
- https://github.com/orma/openroads-vn-tiler/commits/develop?after=ba396e02f3b231f38cd7cc1782c66699249e7ccf+104

**Comment by mileswwatkins** [comment]
Now I'm getting `503 Service Unavailable` errors. It looks like the tiles that `iD` is looking for _do exist_, the tile server's just down or misconfigured? Poking around more now.

**Comment by mileswwatkins** [comment]
Ah, was getting `503`s because of the World Bank firewall. Trying tethered on my cell plan.

**Comment by mileswwatkins** [comment]
During the bit of time that I had today, I couldn't figure out why this was happening for the raster tiles.

It's odd that this is happening for the raster tiles, but not for the vector tiles. The two are generated in roughly the same way:

- `cat ways.sql | sed -e 's/.tmp/'"$WORKDIR"'/g' ways.sql | psql $DATABASE_URL` to dump the database
- `./to-geojson.js $WORKDIR/waynodes.csv $WORKDIR/waytags.csv $WORKDIR/road_properties.csv > $WORKDIR/network.geojson` to unify the dump files into one GeoJSON
- `tippecanoe` to generate the tiles from GeoJSON

This makes me think that the issue could be with the environment variables (especially `$S3_TEMPLATE` in the raster tile worker), or with the settings in `openroads-tilemap` that serves the tiles. More likely the latter, since it looks like all of the tile (ie, z,y,x) coordinates requested by the Editor view _are_ in the production S3 bucket?

Or, it could be that [recent updates to `to-geojson`](https://github.com/orma/openroads-vn-tiler/commits/develop/scripts/to-geojson.js) have been causing problems, and so _both_ the Explore _and_ Editor tiles are broken? I don't have the Devseed Mapbox creds, so I can't check this hypothesis today.

**Comment by olafveerman** [comment]
Posting some notes on my research. I think this is a perforance issue in `openroads-vn-tilemap`.

## Tiler
`openroads-vn-tiler` seems to work correctly:
- it produces new vector tiles on a daily basis
- it pushes them to the correct bucket: `openroads-vn-tiles-prod`
- the tiles contain data:  
`vt2geojson https://s3-ap-southeast-1.amazonaws.com/openroads-vn-tiles-prod/tiles/11/1625/907.vector.pbf > data.geojson`

## Tilemap
`openroads-tilemap` works, albeit very slowly from DC: http://api.openroads-vn.com:3000/#11/20.1191/105.6363
Request for png's remain pending for a long time, and this is in the CloudWatch logs:

`[0mGET /6/54/29.png [32m200 [0m27.086 ms - 150 [0m`

@mileswwatkins Can you confirm that you're seeing the same issues in Vietnam?
@matthewhanson @kamicut

**Comment by mileswwatkins** [comment]
Yes, it does seem like the tile server is working, but just very underpowered, and can't render everything it needs in a short time. I'd noticed the HTTP requests hanging before, but hadn't connected the dots like you!

I'd agree that we need to assign more than a `t2.medium` to this whole setup. But my AWS creds are powerless to check this right now. As soon as someone ups them (requested on #team Slack), I'll see what I can do.

Just a thought: `t2` instances are the weakest, and operate with a limited CPU that has [a "burst" mode](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/t2-instances.html) if extra power is needed. But once the burst credits run out, the instance is relegated to low power (40% of CPU capacity). `m2` or other classes of EC2 would avoid this.

**Comment by olafveerman** [comment]
Upping resources to a `m4.xlarge` didn't help anything. Tiles are generated well initially, but then just remain pending.

Chatted with @mojodna briefly, who gave me some good pointers. His guess is that it's a networking issue, but was also wondering our small `-C` size had anything to do with it.
@kamicut Any reason you chose a small float instead of `0`? That didn't work?

cc @matthewhanson @mileswwatkins

**Comment by olafveerman** [comment]
It seems that using `-C 0` instead of `-C 0.000001` did the trick. Tiles are shown relatively fast again:

![image](https://user-images.githubusercontent.com/751330/31626862-3ce91bea-b279-11e7-9457-1180a19ff2e4.png)

cc @matthewhanson @mileswwatkins @kamicut
