### ISSUE TITLE
Allow users to filter Tasks to a single admin area

### ISSUE THREAD

**Issue by mileswwatkins** [orma/openroads-vn-analytics#213]
This seems like a reasonable request; if a provincial or district official wants to work on fixes only for their admin area, they should be able to filter out all Tasks that don't affect them.

**Comment by mileswwatkins** [comment]
@geohacker: In the Tasks view, allow users to select a particular province, and only view tasks that have at least one road that passes through that province.

This'll probably require you to alter the Tasks database table to include an array of all province IDs that it passes through (add a migration file here https://github.com/orma/openroads-vn-api/tree/develop/db/sql, and also run that migration on the production database using `psql`), and to alter the `generate-tasks.*` workers (https://github.com/orma/openroads-vn-tiler/tree/develop/scripts) so that they calculate that information. The admin areas are stored in the database's `admin_boundaries` table, and since the database is PostGIS-enabled, you should be able to use geospatial queries to do the heavy lifting.

Finally, you'll have to alter the Tasks API routes to accommodate a province parameter, and surface that option as a `<select>` on the front-end.

@dereklieu is a good point of contact for remaining questions on this ticket.

**Comment by geohacker** [comment]
@mileswwatkins this makes sense to me. The alternate proposal I've is: instead of changing the way tasks are generated and the schema of the Tasks table, we can pick the province boundary from the admin table and do an ST_Within on the road geometries in the Task table.

This of course means running a spatial query on the fly. I've much less context to pick either. I wonder if @dereklieu has some thoughts? Thank you!
