### ISSUE TITLE
bbox route null responses

### ISSUE THREAD

**Issue by maxgrossman** [orma/openroads-vn-analytics#246]
the current bbox route has two issues that lead it to return `[null, null, null, null]` responses for some vpromms ids. This is a problem on the front end as it leads to pan/zooming in the search bar to nowhere.

The nuts and bolts of the problem are either...

1) the initial query for `way_id`'s returns nothing

```
select * from current_way_tags
where v='022BH00017';
 way_id | k | v
--------+---+---
(0 rows)
```

or...

2) there aren't any `nodes` associated with the way_id found.

```
{ ways:
   [ anonymous {
       id: '395',
       changeset_id: '21',
       timestamp: 2017-10-13T05:43:33.006Z,
       visible: false,
       version: '1',
       nodes: [],
       tags: [Object] } ],
  waynodes: [],
  members: [],
  nodes: [],
  waytags:
   [ anonymous { way_id: '395', k: 'or_vpromms', v: '022BX00016' },
     anonymous { way_id: '395', k: 'highway', v: 'road' } ],
  nodetags: [],
  relations: [],
  relationtags: [] }
```

An immediate fix could be to quickly make an endpoint that queries the field data geometries table to return a bbox. Or, we could `catch` these null cases on the front end and prevent pan/zooming

**Comment by dereklieu** [comment]
I think the response makes sense for the use cases you describe, and should just be handled in the front-end.

**Comment by mileswwatkins** [comment]
@jameslaneconkling, later this week (when you're done with property CRUD), can you see if this relates to your two remaining tasks (https://github.com/orma/openroads-vn-analytics/issues/311 and https://github.com/orma/openroads-vn-analytics/issues/270)?

**Comment by jameslaneconkling** [comment]
I can't recreate this, but my hunch is that it occurred b/c the logic for determining if a road has a geometry was off.  Now that `hasOSMData` is calculated by checking for visible ways in the `current_ways` table, rather than in the `field_data_geometry` table, the second case shouldn't occur.

That being said, I'd think the route would return a 404 if the bbox didn't exist, either b/c the road didn't exist, or b/c the the road doesn't have a geometry.

**Comment by mileswwatkins** [comment]
Coolio, closing then.
