### ISSUE TITLE
Ambiguity around when task is marked pending

### ISSUE THREAD

**Issue by jameslaneconkling** [orma/openroads-vn-analytics#295]
A task is marked as "Pending" after every edit is submitted (either a dedupe or intersection edit), and is also marked as "Pending" after the user clicks "Finish Task".

This doesn't really cause any huge issues, but does seem redundant.  Presumably, when a user has submitted an edit, but before they click "Finish Task", the task is not necessarily finished, as future edits can be made.

My hunch would be that pending should only be applied on the "Finish Task" click.  Would also simplify the client-server communication logic.

**Comment by dereklieu** [comment]
My thinking was to minimize the chances that a user would see the same tasks over and over again, and also because it seemed unlikely that someone would start a task without completing it. So maybe in this case the `Finish Task` option is what's not needed, and there should be a `Mark as done` option instead that lets you skip a task without seeing it again (aka mark as pending without having taken action).

I'm not totally tied to either approach though, feel free to change it as you feel it's best.

**Comment by jameslaneconkling** [comment]
ah, OK, maybe I misunderstand the `/tasks/pending` route, and the relationship bt/ task ids and way ids.  I now see the `/tasks/pending` route takes way_ids, not task ids.  The two are not equivalent, (way ids and task ids) are they?  Assuming not, does the `/tasks/pending` route mark a task or a way as pending?  If the latter, what does it mean to mark a task pending?

**Comment by dereklieu** [comment]
Yep, the `task_id` is just the pk for the table. It's not the same as the `way_id`. 

I was trying to mitigate the problem of the script creating 5 separate tasks when 5 different ways overlap, and assigning each of the 5 ways what is essentially the same deduping task.

So, when a user fixes one of those tasks, the front-end posts to `tasks/pending` with the `way_id`'s of all 5 ways, so that the next 4 tasks you see aren't duplicates (and also b/c the `way_id` the task was attached to may no longer exist).

I'm not actually sure this is working correctly TBH, but that was the original intention.

**Comment by jameslaneconkling** [comment]
@dereklieu ah OK, that makes sense.  Seems to me the potential redundancy of multiple `tasks/pending` requests might be worth the simplicity of the current approach.

Thanks for the background info.
