### ISSUE TITLE
Inconsistent page size from `/properties/roads` route

### ISSUE THREAD

**Issue by mileswwatkins** [orma/openroads-vn-analytics#354]
Because we do pagination in SQL, but then potentially throw out some rows _after_ SQL, the API response's page size can be less than the desired page size.

**Comment by geohacker** [comment]
This is tricky to fix and we'd have to move away from SQL pagination. I can't think of any undesirable effects due to this, because:

* the desired / max items per page is hardcoded in the backend https://github.com/orma/openroads-vn-api/blob/master/routes/road-properties.js#L19 - this isn't exposed via the API.
* the page count is set on the front-end with 20 as hardcoded https://github.com/orma/openroads-vn-analytics/blob/develop/app/assets/scripts/containers/road-table-container.js#L119, which means that it'll always be more than or equal to total number of pages needed to the entire dataset. 

@danielfdsilva @dereklieu - could you both help me make sure i'm not overlooking anything here to not worry about this?

**Comment by dereklieu** [comment]
Yeah I agree that this probably won't be an issue, but maybe grep the codebase to see if there are any cases where a `limit` is set manually?

**Comment by geohacker** [comment]
@dereklieu thank you! I can't see any references to the limit or page size.
