### ISSUE TITLE
Improve base map in Task

### ISSUE THREAD

**Issue by PCDuc** [orma/openroads-vn-analytics#370]
Base map in Task is lack of information, and the color of road and river are similar, that make it difficult to identify the road.
Can we allow to:
- Choose different base maps?
- Change color contrast between roads and imagery?

![1](https://user-images.githubusercontent.com/31137016/35429142-a9bbb520-026a-11e8-8c5e-df49a50a92c9.jpg)

**Comment by geohacker** [comment]
Another case of map design problem is the following:

![image](https://user-images.githubusercontent.com/371666/39851451-118a5c4c-5441-11e8-8b47-8a92a331793c.png)

Here there are 7 overlapping roads, but the user can only select the top layer. This leads to the task getting added a over 6 subsequent times. 

cc @dereklieu

**Comment by dereklieu** [comment]
@geohacker I think the fact that this creates 7 different tasks is a total bug that should be fixed in this phase of work. This should produce a single deduping task. However, on the actual display of these roads, I'm not sure there's a lot we can do besides make it clear that there are 7 overlapping roads here. 

I've thought about giving each road a different color and decreasing the transparency, but I don't think that would help here. Though I've found that if you zoom in enough, you can start to see daylight between the overlap.

**Comment by geohacker** [comment]
>  I think the fact that this creates 7 different tasks is a total bug 

I don't think this is a bug but more of an undesirable affect because the user can't select two of the roads that are exactly overlapping. So the task will just get added again.

> However, on the actual display of these roads, I'm not sure there's a lot we can do besides make it clear that there are 7 overlapping roads here.

@dereklieu should we find a way to improve selection of layers that are overlapping and maintain a list of currently selected geometries? I'm not sure if that'll improves the current deduping approach.

**Comment by geohacker** [comment]
Other things that has come up in design:
* https://github.com/orma/openroads-vn-analytics/issues/349
* show vpromm ids as text everywhere
* make iD road style and labels consistent 

cc @ricardomestre

**Comment by olafveerman** [comment]
Feedback by AN: The GPROMMS and WON is not well visible on the background of OSM due the not- well contrast symbology. Will it be improved?

cc @geohacker

**Comment by geohacker** [comment]
> The GPROMMS and WON is not well visible on the background of OSM due the not- well contrast symbology. Will it be improved?

I'm unsure about the above feedback. Is this for the Explore page or the Task page? On the task page we're not showing WON. Only the task. 

Explore page:
![image](https://user-images.githubusercontent.com/371666/47713590-ab143700-dc60-11e8-890d-361da1d25c51.png)

**Comment by geohacker** [comment]
We didn't get a clarification - the base improvements are based on the previous recommendations from the team. Closing here.
