### ISSUE TITLE
Explore - black roads are confusing

### ISSUE THREAD

**Issue by sarahantos** [orma/openroads-vn-analytics#389]
When exploring a road, the “Roads without VPRoMMS ID” brings up other, black roads. Can that color be changed (even to something similar, like Dark Gray)? It is confusing because the VPRoMMS roads have black in them (from No Data)

**Comment by geohacker** [comment]
We can't have vpromm roads in another colour but also apply non IRI colour for them since these attributes are not exclusive. This means we'll have to use another style property to indicate whether the road has a vpromm or not at higher zoom levels. I'm trying dashed array as below:

_low zoom level, black can be vpromm with no IRI or just no IRI_
<img width="501" alt="screen shot 2018-02-07 at 5 13 38 pm" src="https://user-images.githubusercontent.com/371666/35914796-a00e52ca-0c2a-11e8-8f25-21949724dc08.png">

_higher zoom. dashes indicate no vprommid. black means no iri_
<img width="575" alt="screen shot 2018-02-07 at 5 13 51 pm" src="https://user-images.githubusercontent.com/371666/35914798-a0398e2c-0c2a-11e8-88e5-9b145ba84799.png">

_when we disable showing non vprommid roads_
<img width="562" alt="screen shot 2018-02-07 at 5 14 01 pm" src="https://user-images.githubusercontent.com/371666/35914799-a0672918-0c2a-11e8-9ce8-4007a22a30b9.png">

I'm open to feedback!

**Comment by geohacker** [comment]
fixed in #408

**Comment by sarahantos** [comment]
Sorry - im slightly confused. So the dashed black roads are roads that have been driven down, but no VPROMM ID was assigned? because if thats the case, wouldn't we have IRI for them?

**Comment by geohacker** [comment]
@sarahantos Not entirely. Dashes and the colours are not related anymore. They both represent different data points.

Dashes - no vprommid.
Black - no IRI. 

There are roads with vprommid with IRI, there are roads without vprommid with IRI, and there are roads without vprommid and no IRI. The only way to capture these combinations is if we use different style properties.
