### ISSUE TITLE
Explore - search function needs some TLC

### ISSUE THREAD

**Issue by sarahantos** [orma/openroads-vn-analytics#391]
Cannot add space when trying in search area (Eg: “Thanh Hóa”)

Search function by Admin only works when we select item from suggestion list (not working when type in then press Enter/or click on search symbol)

Some untranslated words remain in Search function (Eg: “district”, “province”)

**Comment by geohacker** [comment]
Search space problem ticket: https://github.com/orma/openroads-vn-analytics/issues/336
Looks like the search UI is a bit janky.

**Comment by geohacker** [comment]
@danielfdsilva 👋  do you have thoughts on the above problems? Would you consider implementing the search using something like https://jedwatson.github.io/react-select/

**Comment by danielfdsilva** [comment]
The space problem is because of https://github.com/orma/openroads-vn-analytics/blob/master/app/assets/scripts/components/map-search.js#L89

The value should be trimmed only before sending it to the api request

**Comment by geohacker** [comment]
@danielfdsilva - thank you! that explains why. 

So this ticket has three issues:

* [x] no space in search string
* [x] enter doesn't work for search string - going to punt on this for now, because the search is meant to be autocomplete. we should probably add keyboard interaction to the list below.
* [ ] missing translations.

**Comment by geohacker** [comment]
fixed in #407
