### ISSUE TITLE
The task fixit counter rises (instead of drops) as one cleans the network

### ISSUE THREAD

**Issue by PCDuc** [orma/openroads-vn-analytics#420]
![image](https://user-images.githubusercontent.com/31137016/38348352-7da2da3a-38cb-11e8-9eee-0cff5bb48e70.png)

**Comment by geohacker** [comment]
Hey @PCDuc - I just checked this against the production task database and I'm pretty sure this is working as intended. You can see in the gif below, I'm working through the task, and when I click 'Finish task', it removes the tasks from the queue:

![orma-task-count](https://user-images.githubusercontent.com/371666/38619464-d5e1fe90-3db9-11e8-8867-465ddc47c6da.gif)

**Comment by PCDuc** [comment]
Hey @geohacker  I've just tried to clean some roads. It started at 406, then went down to 391 after cleaning, but suddenly jumped back to 403, as you can see now in ORMA. Meanwhile, in your gif, I see you already made it to 397. So, I'm not so sure what's happening.
There are two other strange points that I found and not sure if it's related to the above issue:
- Many roads have exactly the same geometries (bold roads). I suppose that we can only click on the one on top. When we do cleaning for that chosen road, the number of task drops dramatically.
- When doing the remove duplicate function, it mentions "showing 2 roads" for example, but the drop-list of "Select a VPROMMID to apply" shows a long list of VPRoMMS ID.

**Comment by geohacker** [comment]
@PCDuc interesting. Thank you for helping debug this. I'm not sure entire why the task counts go up. Most likely due to a task refresh that happens when the workers run. Let me tag @dereklieu in case he has any ideas.

 
> When doing the remove duplicate function, it mentions "showing 2 roads" for example, but the drop-list of "Select a VPROMMID to apply" shows a long list of VPRoMMS ID.

This was a bug, which I just fixed https://github.com/orma/openroads-vn-analytics/pull/421

**Comment by dereklieu** [comment]
@PCDuc I agree with @geohacker that the count is going up because of a refresh. That is, the task detection runs and loads up the database with any tasks it detects. Once you've made some progress in cleaning the data, by removing duplicates or joining intersections, you should see the total task number go down.

**Comment by PCDuc** [comment]
Hey @dereklieu It's hard for me to say how much time they already spent on fixing data or how many tasks have been finished. I have to ask the local staff who is working with ORMA in tomorrow mission. On the speed, my sense after the last visit in Thanh Hoa is one person can do 50 tasks per day (of course, it depended on the complexity of tasks).

**Comment by geohacker** [comment]
This is fixed.
