### ISSUE TITLE
Misleading tasks?

### ISSUE THREAD

**Issue by geohacker** [orma/openroads-vn-analytics#424]
@PCDuc and I came across a few cases tasks that are confusing - in some of them, there are simply no actions to take, and they get added back to the tasks table even after finishing the task. 

Here's an example:

![image](https://user-images.githubusercontent.com/371666/39851312-5e8d84fc-5440-11e8-865c-9678248d4f06.png)
`id`: 24617701, vpromms 213VL00002, 213VL00003

cc @dereklieu

**Comment by dereklieu** [comment]
Ooh thanks, this is good feedback and suggests the buffer around road endpoints that determine 'should-intersect' is too large.

**Comment by dereklieu** [comment]
For reference, the current threshold is set to 50 meters. I can't tell whether this case is within the threshold or not. If so we can reduce the threshold, if not this would point to a bug somewhere in the task generation script.

**Comment by dereklieu** [comment]
However, this leads me to think that there will always be situations where two roads are very close together, but aren't duplicates and shouldn't intersect - for example, two parallel roads, a turnpike and a service road. 

To solve for this I think we would have to abandon the 'stateless' aspect of the current setup, since as it is, we have no way of permanently (or semi-permanently) marking that this situation should not generate a new task.

**Comment by geohacker** [comment]
@dereklieu right, I think regardless of how we tune the buffer, we'll have to figure out a way to mark a task as 'invalid' and they never show up again.

**Comment by geohacker** [comment]
We fixed this.
