### ISSUE TITLE
[Bug][Map doesn't show in Tasks Page]

### ISSUE THREAD

**Issue by tailm1** [orma/openroads-vn-analytics#570]
Step 1 : Go to Task Tab
http://openroads-vn.com/#/en/tasks
Expected Result : The map is displayed
Actual Result : The Map is not displayed
![image](https://user-images.githubusercontent.com/38553180/53223156-fc7a8300-36a2-11e9-8a51-0d51dac52fc7.png)

**Comment by batpad** [comment]
@geohacker - the map is going to `[0,0]` since there don't seem to be any tasks / it's not getting a valid point to center on. Could you check on the task pipeline, and we can probably just show a message saying "No Tasks" or so when there are no tasks, instead of the current behaviour, which is obviously confusing.

**Comment by geohacker** [comment]
This is because https://github.com/orma/openroads-vn-analytics/issues/574
