### ISSUE TITLE
Search Function is not working after adding asset

### ISSUE THREAD

**Issue by tailm1** [orma/openroads-vn-analytics#595]
Step1 : Add new Asset  : 075CH00009
Step 2 : Go to asset Page 
Step 3 : Search 075CH00009
Expected Result : Get result 
Actual Result : No results available.
![image](https://user-images.githubusercontent.com/38553180/53481932-b2cdd600-3ab0-11e9-8aa9-537ba857aa0c.png)

**Comment by batpad** [comment]
@geohacker both this and the follow up to https://github.com/orma/openroads-vn-analytics/issues/564 are because we fetch and cache the list of vpromms on page load to make search faster.

A straightforward solution here would probably be to just trigger a page reload on asset delete / asset add. @geohacker if that seems reasonable, it should be a simple fix and I can take it on.

@tailm1 can you please confirm for both this and #564, if you reload the page once, search works as expected?

**Comment by tailm1** [comment]
@batpad the search box only works after I reload page again

**Comment by geohacker** [comment]
This is not a high priority issue, but we'll enforce a page reload.
