### ISSUE TITLE
Add analytics and data dumps for lower-level boundaries

### ISSUE THREAD

**Issue by mileswwatkins** [orma/openroads-vn-analytics#78]
Beyond provinces, handle also districts and communes. Make sure to also build the front-end views for these.

For both the analytics URLs and API routes, and the S3 dump URLs, these could follow a nested pattern:

- https://orma.github.io/openroads-vn-analytics/#/analytics/31 for province `31`
- https://orma.github.io/openroads-vn-analytics/#/analytics/31/13 for district `13` within province `31`
- https://orma.github.io/openroads-vn-analytics/#/analytics/31/13/20 for commune `20` within district `13` within province `31`

But this system might not be best if there aren't IDs for district and commune! It would also not work if communes cross district or province borders, or districts cross province borders.

Right now, the analytics don't do any geo processing from boundaries; they just check a VPRoMMS ID for that province's admin ID. This will have to change, and will likely result in a performance tax. Perhaps run questions on this by @kamicut, if it looks like it's going to take a long time.

**Comment by mileswwatkins** [comment]
I assume the 11,000 communes will be difficult; let's skip that level for Analytics and S3 dumps for now, and just do districts and provinces.

**Comment by maxgrossman** [comment]
I talked to @kamicut about approaches for pipelines to generate admin level stats.
Such an pipeline would:

1. dump all ways from the database to GeoJSONs using the data dump script we've already implemented

2. use one of the two approaches two approaches to generate new admin stats tables

    - the previous openraods-worker approach
       - Convert GeoJSONS to mbtiles
       - For each tile generate JSONs that have admin level stats
       - insert these into new admin stats tables

   - a PostGIS approach (as the database has postgis enabled)
      - Create a new table in the database for ways by vpromms_id. All roads without vpromms id could be added with some fake id. 
      - use the current admin tables + postgis_queries to calculate length per admin
      - Take the above step's calculations and insert them into new admin stats tables

I think the 2nd is simpler and will allow for both this ticket and #72 to go hand and hand. I could see an argument for #1 since it makes sure processing is OSM flavor and true to macrocosm, though I'm not sold it has to be.

In either case, once the data is back in the db:

3. Write Endpoints that get these stats per admin + the views to visualize

cc @olafveerman @danielfdsilva

**Comment by mileswwatkins** [comment]
Whoa, actually, it looks like district name is encoded within the VPRoMMS road ID: the fourth and fifth characters (ie, the two letters, that follow the numeric province ID). This document has all of the codes inside, in tabular format:

https://www.dropbox.com/s/79voqnx70u7hvei/Vietnam%20PRoMMS%20Road%20Inventory%20and%20Condition%20Surveys%202011-06-21.docx?dl=0

So, I think that you should make the dumps by just querying the OSM tables for `way`s that have `tag`s for that district ID. **No spatial querying should be necessary for analytics in phase 1, no need to over-architect.**

**Comment by mileswwatkins** [comment]
Also, if these analytics are going to be calculated by-road-ID, then you can just save the results in the `road-properties` table's `properties` JSONB key, for that road ID. No need to create a new table.

**Comment by mileswwatkins** [comment]
Analytics implemented, data dumps still in progress in https://github.com/orma/openroads-vn-analytics/issues/125
